strings:
  inputs: ../Resources/Localization/en.lproj
  filter: .+\.strings$
  outputs:
    - templateName: structured-swift4
      output: ../Resources/Generated/Strings.swift
      params:
        publicAccess: true
xcassets:
  inputs: ../Resources/Assets.xcassets
  outputs:
    - templateName: swift4
      output: ../Resources/Generated/assets-images.swift
      params:
        publicAccess: true
